### ISSUE TITLE
Change mail content

### ISSUE THREAD

**Issue by AngBriz** [ikseth/cyclops#1]
Hi man!

I have problems with automatic mails. I want to change the content of the mail, to show procedures to remote operators in case of success of repair action. (message "repair action ok, please change to up if status is ok"

I tried to search about "mail", "mailx", in case of my customer also I search for "admonhpc" the sender of the mails.

I try to search info in cyclops.sh and audit.nod.sh scripts.

Thanks!

**Comment by AngBriz** [comment]
Hi again!

Maybe I have to change /opt/cyclops/tools/testing/sensors.nodes.mon.sh in order to add more text in lines _msg_insert="repair action ok, please change to up if status is ok". Is it ok?

` if [ "$_node_rzr_status" == "0" ] || [ "$_node_rzr_status" == "21" ]
                                then
                                        _msg_insert="repair action ok, please change to up if status is ok. In order to change node status, please, follow procedure SFCYBS0002 : Cambiar el estado de los Nodos en Cyclops"
                                        $_script_path/cyclops.sh -a diagnose -n $_node_name -c 2>&1 >/dev/null
                                        $_script_path/audit.nod.sh -i event -e reactive -m $_msg_insert -s UP -n $_node_name 2>>$_mon_log_path/audit.log
                                        $_script_path/cyclops.sh -p medium -m $_node_name" : "$_msg_insert -l
                                else
                                        _msg_insert="repair action fail, please change to drain if status is bad and productive environment is ok. In order to change node status, please, follow procedure SFCYBS0002 : Cambiar el estado de los Nodos en Cyclops"
                                        $_script_path/cyclops.sh -a content -n $_node_name -c 2>&1 >/dev/null
                                        $_script_path/audit.nod.sh -i event -e reactive -m $_msg_insert -s CONTENT -n $_node_name 2>>$_mon_log_path/audit.log
                                        $_script_path/cyclops.sh -p high -m $_node_name" : "$_msg_insert -l
`

** sorry, I try to put github code font and show as plain text...**

Thanks in advance!

**Comment by ikseth** [comment]
Hi,

we are working on customizable messages.

be on news updates because next we publish new features and you ask for one we incluye

thank you
regards

**Comment by ikseth** [comment]
Hi,

We have date for new updateswe publish new updates, with fixes , new features, and more.

Next Sunday.

Please wait for it to update your cyclops.

Thank you
