### ISSUE TITLE
Alerts Error

### ISSUE THREAD

**Issue by AngBriz** [ikseth/cyclops#11]
Hi,

We received in our cyclops installation following error:

> Cyclops System Detect this system alerts active:
> 
>                 20-03-2020 04:20: Host: timeout: Sensor:  [timeout] - Alert Active

We cannot found the root cause of that issue, but this isuee include new line to the file **/opt/cyclops/monitor/sensors/data/status/stateofthings.cyc** 

The line included is:

> ALERT;NOD;1;timeout; [timeout];1584678009;1

Do you know how can we solve this? is it a false positive alert?

Thank you in advance.

Angel & Stefan

**Comment by ikseth** [comment]
This is old bug, now is solved, please update.

**Comment by ikseth** [comment]
Try new update procedure: https://github.com/ikseth/cyclops/blob/master/update_method.txt
