### ISSUE TITLE
Logrotate

### ISSUE THREAD

**Issue by AngBriz** [ikseth/cyclops#2]
We have severity problem with logs size.

It will be helpfull if logrotate will be implemente in /opt/cyclops/logs folder ;)

Thank you in advance

log rotate works fine if you configure it with linux daemon. 
we are working in new feature for you can ask for data y log rotate files

**Comment by ikseth** [comment]
you can configurate logrotate in /opt/cyclops/logs as any linux type of log.

The only thing now if you configure logrotate you lost history traceability, we are working on stats.cyclops.logs.sh to be able to read old compressed files generated by log rotate.

Please if you don't want to lose much more traceability try to keep one year at least

Thank you

**Comment by ikseth** [comment]
Now cyclops has new feature and support logrotate compress formats like xz and gz.

You can use logrotate config like this ( for example )

/opt/cyclops/logs/*.log
{
    su cyclops cyclops
    compress
    dateext
    maxage 365
    rotate 99
    missingok
    notifempty
    size +4096k
    create 640 cyclops cyclops 
    sharedscripts
    postrotate
        /usr/bin/systemctl reload syslog.service > /dev/null
    endscript
}

**Comment by ikseth** [comment]
Cyclops is operative with compressed logrotate files. this issue is close
